/**
 * Content Collections — Insights.
 *
 * Editorial commentary in Dayel Ostraco's voice: technical and strategic
 * perspective on agentic AI, identity, and shipping inside the federal
 * boundary. Single-author site: no author registry, no author field.
 * The byline is hardcoded on the templates.
 *
 * Surfaces via the /insights index page, individual post routes, and
 * an RSS feed. Empty by default at scaffolding time; the index page
 * renders an empty-state stub until posts land.
 */
import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';

const insights = defineCollection({
    loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/insights' }),
    schema: ({ image }) => z.object({
        title: z.string(),
        // Optional query-shaped <title> tag override (editorial `title`
        // stays the H1/OG headline). Pattern: "Editorial Line: keyword
        // clause". Falls back to `title` when unset.
        seoTitle: z.string().optional(),
        date: z.coerce.date(),
        // Optional last-substantive-edit date. Feeds BlogPosting
        // dateModified (falls back to `date`).
        updated: z.coerce.date().optional(),
        summary: z.string().min(60).max(280),
        tags: z.array(z.string()).optional(),
        // Optional series membership. Posts sharing a series name get a
        // "Part N of M" badge and ordered prev/next navigation (M is
        // computed from the collection, so adding part 4 updates all
        // siblings automatically).
        series: z.object({
            name: z.string(),
            part: z.number().int().positive(),
        }).optional(),
        readTime: z.string().optional(),
        // Hero image: co-located with the post directory and referenced
        // via a relative path (e.g., './hero.webp'). image() validates
        // the path resolves and gives the templates a typed asset to
        // pass into Astro's <Image> component for auto-optimization.
        heroImage: image().optional(),
        heroImageAlt: z.string().optional(),
        draft: z.boolean().default(false),
        // OG image convention: /assets/img/og/og-insights-<slug>.png,
        // generated by scripts/og/render.mjs (see Task 3). Override
        // per-post with an explicit path when needed.
        ogImage: z.string().optional(),
        // Optional substring of `title` to render in the accent color
        // on the generated OG card.
        ogAccent: z.string().optional(),
        // Optional body-band section watermark. Renders as ambient
        // mono caps behind the article body. Defaults to "/ESSAY"
        // in the template. Set per-post to echo the post's thesis.
        bodyWatermark: z.string().optional(),
    }),
});

export const collections = { insights };
